-- Supabase schema for the GitHub Pages shared visit/gameplay stats.
-- Run this once in Supabase SQL Editor before deploying the Edge Function.

create table if not exists public.sessions (
  id bigint generated by default as identity primary key,
  session_id text unique not null,
  nickname text not null,
  balance integer default 10000,
  debt integer default 0,
  completed_count integer default 0,
  scam_count integer default 0,
  recovery_used_count integer default 0,
  total_recovered integer default 0,
  total_earned integer default 0,
  total_lost integer default 0,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create table if not exists public.level_results (
  id bigint generated by default as identity primary key,
  session_id text not null references public.sessions(session_id) on delete cascade,
  level_id integer not null,
  start_balance integer,
  end_balance integer,
  delta integer,
  is_scammed integer default 0,
  trap_count integer default 0,
  main_tactic text,
  created_at timestamptz default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  session_id text not null references public.sessions(session_id) on delete cascade,
  level_id text,
  event_type text,
  trap_code text,
  trap_name text,
  tactic text,
  amount_change integer default 0,
  balance_after integer default 0,
  debt_after integer default 0,
  severity integer default 1,
  note text,
  created_at timestamptz default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  session_id text not null references public.sessions(session_id) on delete cascade,
  level_id text,
  amount integer not null,
  reason text,
  balance_after integer,
  created_at timestamptz default now()
);

create table if not exists public.visits (
  id bigint generated by default as identity primary key,
  visitor_id text not null,
  visited_at timestamptz default now(),
  visit_date date default current_date
);

create table if not exists public.active_visitors (
  visitor_id text primary key,
  last_seen_at timestamptz default now()
);

create table if not exists public.level_plays (
  id bigint generated by default as identity primary key,
  visitor_id text,
  session_id text,
  level_id integer not null,
  played_at timestamptz default now(),
  play_date date default current_date
);

create index if not exists idx_events_session on public.events(session_id);
create index if not exists idx_events_recent on public.events(id desc);
create index if not exists idx_level_session on public.level_results(session_id);
create index if not exists idx_level_id on public.level_results(level_id);
create index if not exists idx_tx_session on public.transactions(session_id);
create index if not exists idx_visits_date on public.visits(visit_date);
create index if not exists idx_active_last_seen on public.active_visitors(last_seen_at);
create index if not exists idx_level_plays_level on public.level_plays(level_id);

alter table public.sessions enable row level security;
alter table public.level_results enable row level security;
alter table public.events enable row level security;
alter table public.transactions enable row level security;
alter table public.visits enable row level security;
alter table public.active_visitors enable row level security;
alter table public.level_plays enable row level security;

-- No public RLS policies are needed. The Edge Function uses SUPABASE_SERVICE_ROLE_KEY
-- on the server side, so browser users cannot write directly to these tables.
